### ISSUE TITLE
Component display umbrella issue

### ISSUE THREAD

**Issue by follower** [Omniblox/Eagle-Loader#5]
Questions to answer:
- [x] _Does existing parsing code extract & store all relevant details (e.g. location, orientation, package) from `.brd` file?_
  
  Location and orientation appears to be stored as does a reference to the package by name--but not necessarily a direct mapping to a model.
- [X] _How do we associate a 3D model with a particular component?_
  
  Still needs to be determined. For designs that use component libraries with associated 3D models (e.g. SparkFun) it may be able to be determined "automatically".

  For now we use a mapping from component name to model file path.

- [X] _What 3D model format(s) do we want to support? e.g. `.stl`_
  
  Three.js supports loading of a number of model formats with various feature support. It has a preferred format itself which might require use of conversion tools.

  Answer: Initial support is to be `.stl` only.

- [X] _What should the relationship between connectors and models be?_
  
  Connectors are attached to models, centred on the bottom face.

- [X] _What is the relationship between connectors, components, models and pads?_
  
  Still to be investigated--but it appears one connector per component except when the component itself is a physical connector.

   Understood enough for now.

- [X] _How sophisticated do we want the component rendering to be? e.g. texture, material, etc_
  
  Answer: Initial `.stl` support means single material support is acceptable.

**Comment by follower** [comment]
#8 and #10 cover implementation of this now.
